name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
        gemfile:
          - gemfiles/Gemfile.rails7.0
          - gemfiles/Gemfile.rails6.1
          - gemfiles/Gemfile.rails6.0
        bundler:
          - "2"
        exclude:
          - ruby: "3.1"
            gemfile: gemfiles/Gemfile.rails6.0
          - ruby: "3.0"
            gemfile: gemfiles/Gemfile.rails6.0
        include:
          - ruby: "2.7"
            gemfile: gemfiles/Gemfile.rails6.0
          - ruby: "2.6"
            gemfile: gemfiles/Gemfile.rails6.0
          - ruby: "2.6"
            gemfile: gemfiles/Gemfile.rails5.2
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
